config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {registrations: 'students/registrations',
  sessions: 'students/sessions', passwords: 'students/passwords'}
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "students#index"

  #devise_for :student
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    validates :first_name, presence: true
    validates :last_name, presence: true
    # validates :school_email, presence: true, uniqueness: true, format: {with: /\A[\w+\-.]+@msudenver\.edu\z/i, message: "Must be an @msudenver.edu email!"}
    validate :email_format
    validates :major, presence: true
    validates :minor, presence: true
    validates :graduation_date, presence: true
    has_one_attached :image
    after_destroy :purge_image
    validate :acceptable_image

    #List of Valid Majors a student or employer can choose
    VALID_MAJORS = ["Computer Engineering BS", "Computer Information Systems BS",
        "Computer Science BS", "Cybersecurity Major", "Data Science and Machine Learning Major"]

    validates :major, inclusion: {in: VALID_MAJORS, message: "%{value} is not a valid major"}

    #image purger for seeding
    private
    def purge_image
        image.purge_image if image.attached?
    end

    def email_format
        unless email =~ /\A[\w+\-.]+@msudenver\.edu\z/i
            errors.add(:email, "Must be an @musdenver.edu email address")
        end
    end

    def acceptable_image
        return unless image.attached?
                  
        unless image.blob.byte_size <= 10.megabyte
            errors.add(:image, "file size is too big, must be under 10 MB.")
        end
    
        acceptable_types = ["image/jpeg", "image/png"]
        unless acceptable_types.include?(image.content_type)
            errors.add(:image, "must be a JPEG or PNG")
        end
    end
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  # def index
  #   @students = Student.all
  # end

  def index
    #Search by major and Grad date
    Rails.logger.info "Params: #{params.inspect}"

    @search_params = params[:search] || {}
    @students = Student.all

    Rails.logger.info "Search Params: #{@search_params.inspect}"
    #If statement for major search
    if params[:show_all] == "true"
      @students = Student.all
    elsif @search_params[:major].present?
      if @search_params[:major] == 'Any Major'
        @students = Student.all
      else
        @students = @students.where(major: @search_params[:major])
      end
    end
    #If statement for grad date search
    if @search_params[:graduation_date].present? && @search_params[:graduation_date_compare].present?
      if @search_params[:graduation_date_compare] == 'before'
        @students = @students.where('graduation_date < ?', @search_params[:graduation_date])
      elsif @search_params[:graduation_date_compare] == 'after'
        @students = @students.where('graduation_date > ?', @search_params[:graduation_date])
      end
    end
    #If no major or grad date show no students
    if @search_params[:major].blank? && @search_params[:graduation_date].blank?
      @students = Student.none
    end
end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, #:school_email,
       :major, :minor, :graduation_date, :image)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <!-- <div> -->
  <!-- <%= form.label :school_email, style: "display: block" %> -->
  <!--  <%= form.text_field :school_email %> -->
  <!-- </div> -->

  <div>
    <%= form.label :major, style: "display: block" %>
    <%= form.select :major, options_for_select(Student::VALID_MAJORS), {prompt: "Select a Major"} %>
  </div>

  <div>
    <%= form.label :minor, style: "display: block" %>
    <%= form.text_field :minor %>
  </div>

  <div>
    <%= form.label :graduation_date, style: "display: block" %>
    <%= form.date_field :graduation_date %>
  </div>

  <div class ="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_search_form.html.erb
<%= form_with(url: students_path, method: :get, local: true, class: "form-inline") do |form|%>
    <!-- Actual search function -->
    <div>
        <%=form.label :major, "Select Major", class: "form-label" %>
        <%=form.select :major, options_for_select(["Any Major"] + Student::VALID_MAJORS, 
        @search_params[:major]), {prompt: "Select a Major"}, name:'search[major]',
        class: "form-control" %>
    </div>
    
    <!-- Before or After selector -->
    <div>
        <%=form.label :graduation_date, "Select Before or After the Graduation Date", class: "form-label" %>
        <%=form.select :graduation_date_compare, options_for_select([['Before', 'before'], ['After', 'after']]), {prompt: "Select Before or After"}, name:'search[graduation_date_compare]',
        class: "form-control" %>
    </div>

    <!-- Grad date Selector -->
    <div>
        <%=form.label :graduation_date, "Graduation Date", class: "form-label" %>
        <%=form.date_field :graduation_date, name:'search[graduation_date]',
        class: "form-control" %>
    </div>

    <!-- Search button-->
    <div>
        <%=form.submit "Search", class: "btn btn-primary" %>
    </div>

    <!-- show all button -->
    <div>
        <%= link_to "Show All",students_path(show_all: true), method: :get, class: "btn btn-secondary" %>
    </div>

    <!-- Bootstrap List for search results --> 
    <div>
        <h3>Search Results:</h3>
        <table class="table table-striped table-hover">
            
        <thead>
            <tr>
            <th>Profile Picture</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Major</th>
            <th>Graduation Date</th>
            <th colspan="3">Actions</th>
            </tr>
        </thead>
            <% @students.each do |student| %>
            <tr>
                <td>
                    <% if student.image.attached? %>
                        <%= image_tag student.image.variant(resize_to_limit:[150, nil]) %>
                    <% else %>
                        <%= image_tag("default.png", size: "50x50") %>
                    <% end %>
                </td>
                <td><%= student.first_name %></td>
                <td><%= student.last_name %></td>
                <td><%= student.major %></td>
                <td><%= student.graduation_date.strftime("%b %d, %Y") if student.graduation_date %></td>
                <td><%= link_to 'Show', student, class: 'btn btn-info btn-sm' %></td>
                <td><%= link_to 'Edit', edit_student_path(student), class: 'btn btn-warning btn-sm' %></td>
                <td><%= button_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger btn-sm' %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
        
        <!-- Show no students -->
        <% if @students.empty? %>
            <p class = "alert alert-warning">No students found. Please enter search criteria to find students.</p>
        <% end %>
        </div>
<% end %>

app/views/students/_student.html.erb
<!--
<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <!-- <p> -->
  <!-- <strong>School email:</strong> -->
  <!-- <%= student.school_email %> -->
  <!-- </p> -->

  <p>
    <strong>Major:</strong>
    <%= student.major %>
  </p>

  <p>
    <strong>Minor:</strong>
    <%= student.minor %>
  </p>

  <p>
    <strong>Graduation date:</strong>
    <%= student.graduation_date %>
  </p>

  <% if student.image.attached? %>
    <%= image_tag student.image.variant(resize_to_limit:[150, nil]) %>
  <% else %>
    <%= image_tag("default.png", size: "150x150") %>
  <% end %>
  
</div>
-->

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<!-- Provide a summary banner and search form -->
<div class="d-block p-2 text-bg-primary">Provide a summary</div>

<%= render 'search_form', search_params: @search_params %>

<!-- Used ERB comments to change back remove # and replace with = except
at student do and end-->
<div id="students">
  <%# @students.each do |student| %>
    <%# render student %>
    <p>
      <%# link_to "Show this student", student %>
    </p>
  <%# end %>
</div>

<%= link_to "New student", new_student_path %>



app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>